#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if ! git diff HEAD^ HEAD --exit-code -- ./package.json; then
  echo "📦 package-lock.json changed. Running npm install to bring your dependencies up to date."
  npm install
fi
